<a href="https://colab.research.google.com/github/Huhhuu/DataDeepLearning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

my_list = [1, 9, 15, 39]
print('Python list:', my_list)
my_num_array = np.array(my_list)
print('Numpy array:', my_num_array)

a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


In [8]:
import numpy as np

c = np.array([(1, 2, 3), (4, 5, 6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [9]:
import numpy as np

d = np.array([[[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]]])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]]]
(1, 4, 3)


In [ ]:
import numpy as np


e = np.zeros((2, 2))
f = np.ones((3, 3))
