<a href="https://colab.research.google.com/github/Huhhuu/DataDeepLearning/blob/main/Tuan1_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [9]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
r1 = tf.constant(9,tf.int16)
print(r1)
r1_float =tf.constant(1.12,tf.float32)
print(r1_float)
r1_string=tf.constant('Hello HUIT University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello HUIT University', shape=(), dtype=string)


In [10]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [11]:
rank_2_tensor = tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float16)
print(rank_2_tensor)


tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [12]:
rank_3_tensor = tf.constant([[[0,1,2,3,4],[5,6,7,8,9]],[[10,11,12,13,14],[15,16,17,18,19]],[[20,21,22,23,24],[25,26,27,28,29]]])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [13]:
t_3_zero = tf.zeros([3,3,5])
print(t_3_zero)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


In [14]:
t_one = tf.ones(10)
print(t_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)


In [15]:
range_tensor = tf.range(3.0,7.0,delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


In [19]:
range_tensor = tf.random.normal([3,3])
print(range_tensor)

tf.Tensor(
[[-0.28329736 -1.8955132  -1.1470977 ]
 [-0.05171737 -0.19325738  0.523303  ]
 [ 0.18358438 -0.5936887  -0.01660298]], shape=(3, 3), dtype=float32)


In [24]:
range_tensor = tf.random.uniform([5],minval=10,maxval=20)
print(range_tensor)
print(tf.random.shuffle(range_tensor))

tf.Tensor([10.829563 10.697542 14.036907 12.922035 18.91728 ], shape=(5,), dtype=float32)
tf.Tensor([12.922035 14.036907 10.829563 18.91728  10.697542], shape=(5,), dtype=float32)


In [26]:
a= tf.constant([6., 6., 6.])
b = tf.constant([4., 4., 4.])
c = tf.constant([3., 3., 3.])
d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g= tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)
print(i)
print(l)

tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


In [27]:
t1 = tf.constant ([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],[4, 5, 6]])
t4 = tf.constant([[7, 8],[9, 10],[11, 12]])
dot_x = tf.tensordot (t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)
print(t1)
print(t2)
print(t3)
print(t4)
cross = tf.linalg.cross (t1, t2)
mm = tf.matmul(t3, t4)
d= tf.linalg.diag(t3)
trace= tf.linalg.trace(t3)
trans= tf.transpose(t3)
eye= tf.eye(5, 5)
print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)
