<a href="https://colab.research.google.com/github/Huhhuu/DataDeepLearning/blob/main/Tuan1_numpy-pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

my_list = [1, 9, 15, 39]
print('Python list:', my_list)
my_num_array = np.array(my_list)
print('Numpy array:', my_num_array)

a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


In [8]:
import numpy as np

c = np.array([(1, 2, 3), (4, 5, 6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [9]:
import numpy as np

d = np.array([[[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]]])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]]]
(1, 4, 3)


In [10]:
import numpy as np

e = np.zeros((2, 2))
f = np.ones((3, 3))

print('Zero matrix:\n',e)
print('One matrix\n',f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
import numpy as np

e = np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
f=e.reshape(3,2)
print(f)
g=np.array([[[1.,2.,3.],[4.,5.,6.]],[[7.,8.,9.],[10.,11.,12.]]])
print(g)
print(g.shape)
h=g.reshape(3,4)
print('reshape (3,4)\n',h)
j = g.reshape(3,2,2)
print('reshape (3,2,2)\n',j)
k = g.reshape(2,3,2)
print('reshape (2,3,2)\n',k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3,2,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [14]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [15]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
print('Thêm ngang\n', h_stack)
v_stack = np.vstack((f, g))
print('Ghi dọc\n', v_stack)

Thêm ngang
 [1. 2. 3. 4. 5. 6.]
Ghi dọc
 [[1. 2. 3.]
 [4. 5. 6.]]


In [41]:
a = np.random.randint(100, size=(5,))
print('Mảng 1-D chiều ngẫu nhiên\n',a)
b = np.random.randint(100, size=(3, 4))
print('Mảng 2-D chiều ngẫu nhiên\n',b)
c = np.random.randint(100, size=(3, 4, 3))
print('Mảng 3-D chiều ngẫu nhiên\n',c)

Mảng 1-D chiều ngẫu nhiên
 [87 40 47 43 51]
Mảng 2-D chiều ngẫu nhiên
 [[61 21 63 13]
 [58 98 61 99]
 [58 53 70 29]]
Mảng 3-D chiều ngẫu nhiên
 [[[16 18  4]
  [61 90 41]
  [51 64 99]
  [67 66  9]]

 [[80 58 76]
  [97  6 27]
  [24 40 68]
  [60 69 29]]

 [[94 56 17]
  [72 94 79]
  [51 91 59]
  [87 42 49]]]


In [45]:
a = np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)
b=np.random.choice([2,4,6,8,10,12,14,16,18,20], size= (3,5))
print(b)

18
[[14 20 20  2  6]
 [12  2 12  6 10]
 [12 14 10 12  8]]


In [46]:
import pandas as pd

a = pd.Series([1.,2.,3.])
print(a)
print('First value:',a[0])
b=pd.Series([1.,2.,3.], index=['a','b','c'])
print(b)
print('First value:',b['a'])

calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


In [47]:
h = np.array([[1,2],[3,4]])
df_h =pd.DataFrame(h)
print('DataFrame:\n', df_h)

numpy_h = np.array(df_h)
print('Numpy array:\n', numpy_h)

DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [48]:
dic = {'Name':['John','Smith'], 'Age':[30,40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [53]:
r = np.random.randn(20,4)
df = pd.DataFrame(r,columns = ['so1', 'so2', 'so3', 'so4'])
print(df.head())

        so1       so2       so3       so4
0 -0.312923 -2.095439  0.170487 -0.522435
1  0.248949 -0.146306 -0.748854  1.187388
2  2.202696  1.182328  0.535815 -0.749155
3  0.217512  1.798785  1.255382  0.159310
4  1.043579 -0.136591  0.638294  1.616198


In [63]:
r = np.random.randn(20,4)
df = pd.DataFrame(r,columns = ['so1', 'so2', 'so3', 'so4'])
print(df.head())

print('Chon cot so1\n',df['so1'])

print('Chon nhieu dong\n',df[0:3])

print('Chon nhieu cot\n', df[['so1','so3']])

        so1       so2       so3       so4
0 -1.837687 -0.621577 -0.215520 -0.338720
1 -0.125025 -1.047584  0.107575 -0.943693
2 -0.105614 -1.470310  1.212974  1.004672
3 -1.234617 -0.669844  0.315480  0.529711
4  0.131005  0.492806  1.909760 -0.373093
Chon cot so1
 0    -1.837687
1    -0.125025
2    -0.105614
3    -1.234617
4     0.131005
5    -0.377060
6     1.222772
7     0.379466
8     0.716922
9     0.473612
10    0.060392
11    0.388124
12    0.521459
13   -1.973563
14   -0.438270
15    1.414369
16    0.276106
17   -0.560501
18    0.038330
19   -0.222249
Name: so1, dtype: float64
Chon nhieu dong
         so1       so2       so3       so4
0 -1.837687 -0.621577 -0.215520 -0.338720
1 -0.125025 -1.047584  0.107575 -0.943693
2 -0.105614 -1.470310  1.212974  1.004672
Chon nhieu cot
          so1       so3
0  -1.837687 -0.215520
1  -0.125025  0.107575
2  -0.105614  1.212974
3  -1.234617  0.315480
4   0.131005  1.909760
5  -0.377060  0.990950
6   1.222772 -0.090864
7   0.379466 -0.976028


In [66]:
path = 'https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/refs/heads/main/Data/23_HOMES.csv'
COLUMNS = ['Selling_Price', 'List_Price']
df_csv = pd.read_csv(path, skipinitialspace=True, usecols=COLUMNS)
print(df_csv.head())
print(df_csv.tail())
df_csv1 = pd.read_csv(path, skipinitialspace=True, usecols=COLUMNS, nrows=10)
print(df_csv1.head())
print(df_csv1.tail())

   Selling_Price  List_Price
0         400000      414000
1         370000      379000
2         382500      389900
3         300000      299900
4         305000      319900
    Selling_Price  List_Price
35         253000      259900
36         310000      314900
37         300000      309900
38         295000      295000
39         478000      479000
   Selling_Price  List_Price
0         400000      414000
1         370000      379000
2         382500      389900
3         300000      299900
4         305000      319900
   Selling_Price  List_Price
5         320000      319900
6         321000      328900
7         445000      450000
8         377500      385000
9         460000      479000


In [68]:
path = 'https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/refs/heads/main/Data/23_HOMES.csv'
df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv.head())
print(df_csv.groupby(['Rooms']).mean().head())
print(df_csv.groupby(['Rooms'])['Baths_full'].min().head())

   Selling_Price  List_Price  Area  Acres  Age  Taxes  Rooms  Bedrooms  \
0         400000      414000  2704   2.27   27   4920      9         3   
1         370000      379000  2096   0.75   21   4113      8         4   
2         382500      389900  2737   1.00   36   6072      9         4   
3         300000      299900  1800   0.43   34   4024      8         4   
4         305000      319900  1066   3.60   69   3562      6         3   

   Baths_full  
0           3  
1           2  
2           2  
3           2  
4           2  
       Selling_Price     List_Price    Area     Acres   Age        Taxes  \
Rooms                                                                      
4      268000.000000  275000.000000  1196.0  0.830000  44.0  3360.000000   
5      214900.000000  219900.000000  1635.0  0.250000  49.0  2560.000000   
6      298950.000000  305750.000000  1565.1  2.004000  56.2  3424.000000   
7      318666.666667  322966.666667  1694.5  3.261667  40.0  4210.166667   
8  